where-to-hike:
  notifications:
    logger:
       enabled: true

server.port: 8085

spring:
  cloud: 
    stream:
      function:
        definition: notifyAvailability
      bindings: 
        notifyAvailability-in-0: 
          destination: where-to-hike-search-result
          group: where-to-hike-notify-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000 