apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-to-hike-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-to-hike
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
    subPath: where-to-hike-crawler