apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-to-hike-api-gateway
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=where-to-hike-api-gateway"
spec:
  type: service
  lifecycle: experimental
  owner: where-to-hike-team
  system: where-to-hike
  dependsOn: 
    - component:where-to-hike-ui
